### PR TITLE
use docker alpine-node

### PR DESCRIPTION
**Pull request by tnguyen14**
Just a suggestion to run this as a docker container. Any feedback is welcome. 

/cc @aredridel

### CODE REVIEW

**Comment by aredridel** [comment]
Could do, but I don't have a docker host to run it on, and I don't think it adds any benefit, just raises the overhead of running the tool.

**Comment by tnguyen14** [comment]
Agreed about raising overhead. My thought was that this adds the ability to use docker without forcing it. I could remove the changes in the README?

**Comment by aredridel** [comment]
What changes in the readme?

**Comment by aredridel** [comment]
Yeah, that'd make sense. Perhaps separate "how to run with docker" instructions?

**Comment by tnguyen14** [comment]
I've updated the commit with just a separate how to run with docker instructions.

**Comment by aredridel** [comment]
Oh very nice!

**Pull request merged**
